name: Deploy
on:
  push:
    tags:
      - 'v[0-9].*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: ${{ secrets.TARGET }}
          ARGS: '-rlgoDzvc -i --exclude=.env --delete'
          SCRIPT_AFTER: 'cd ${{ secrets.TARGET }} && npm ci && ~/.npm-global/bin/pm2 restart "Actions Demo"'
          SCRIPT_AFTER_REQUIRED: true

